routes:
  /test/: test

collections:
  /industry/:
    permalink: /industry/{slug}/
    template: indexii
    filter: tag:hash-industry

  /:
    permalink: /{slug}/
    template: index
    filter: tag:hash-just

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
